### ISSUE TITLE
Vultc not found...

### ISSUE THREAD

**Issue by wehrend** [DatanoiseTV/PicoADK-Firmware-Template#18]
**Describe the bug**
Vultc in /project/tools/vultc cannot be found although it is there.

**To Reproduce**
,/build_firmware_setup.sh
...
[7/91] Transcompiling Vult DSP Code to C++.
/bin/sh: /project/tools/vultc: not found
ninja: job failed: cd /project/build && /project/tools/vultc /project/vultsrc/dsp.vult -i /project/lib/vult/examples/osc -i /project/lib/vult/examples/util -i /project/lib/vult/examples/filters -i /project/lib/vult/examples/env -i /project/lib/vult/examples/midi -i /project/lib/vult/examples/effects -i /project/lib/vult/examples/units -ccode -real fixed -samplerate 44140 -o vult
ninja: subcommand failed

./vultc
vult v0.4.14 - https://github.com/modlfo/vult
no input files

**Comment by DatanoiseTV** [comment]
Hi,
Are you trying to compile on a raspberry pi? Can you try running it without docker?

**Comment by wehrend** [comment]
No, I am running it on a standard Desktop PC.

I will try to run it without Docker and see if it helps...

**Comment by wehrend** [comment]
This (running without Docker) worked.
Thank you!

Sven Wehrend

**Comment by wehrend** [comment]
it worked out of the box on my laptop. With some workarounds (like copying my system copy of vultc over the once based in tools), I've got it working on my Desktop, too. Closing the issue.
